/**
 * Scaffolder — creates a new Next.js project from the ai-platform-template,
 * updates vertical.config.ts, creates a GitHub repo, and pushes code.
 */
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { ScopedIdea, LaunchedProduct } from './types.js';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN || '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';
const GITHUB_USER = 'infosiva';
const TEMPLATE_PATH = '/root/agents/kwizzo'; // Use kwizzo as template base (ai-platform-template not present)
const AGENTS_DIR = '/root/agents';

function slugify(title: string): string {
  return title.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
}

async function createGitHubRepo(repoName: string, description: string): Promise<string | null> {
  try {
    const res = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `token ${GITHUB_TOKEN}`,
        'User-Agent': 'business-agent',
      },
      body: JSON.stringify({
        name: repoName,
        description,
        private: false,
        auto_init: false,
      }),
    });
    if (!res.ok) {
      const err = await res.text();
      console.error(`    [GitHub] Create repo failed: ${err.slice(0, 200)}`);
      return null;
    }
    const data = await res.json() as any;
    return data.clone_url || null;
  } catch (e: any) {
    console.error(`    [GitHub] Error: ${e.message}`);
    return null;
  }
}

function addToWatchdog(siteEntry: object): void {
  const configPath = '/root/site-watchdog/websites.config.json';
  if (!fs.existsSync(configPath)) return;
  const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  config.sites.push(siteEntry);
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf8');
  console.log('    [Watchdog] Added new site to websites.config.json');
}

export async function scaffoldProduct(idea: ScopedIdea): Promise<LaunchedProduct | null> {
  const slug = slugify(idea.title);
  const repoName = slug;
  const projectPath = path.join(AGENTS_DIR, slug);

  console.log(`\n  Scaffolding: "${idea.title}" at ${projectPath}`);

  // Skip if already exists
  if (fs.existsSync(projectPath)) {
    console.log(`    [Skip] Directory already exists: ${projectPath}`);
    return null;
  }

  try {
    // 1. Copy template (use kwizzo as base since ai-platform-template not present)
    // Try multiple template sources in order
    const templateCandidates = [
      '/root/agents/kwizzo',
      '/root/agents/nudge',
      '/root/agents/questly',
    ];
    const templateSrc = templateCandidates.find(t => fs.existsSync(t));
    if (!templateSrc) {
      console.error('    [Scaffold] No template found');
      return null;
    }

    console.log(`    Copying template from ${templateSrc}...`);
    execSync(`cp -r "${templateSrc}" "${projectPath}"`, { stdio: 'pipe' });

    // 2. Remove old git history
    const gitDir = path.join(projectPath, '.git');
    if (fs.existsSync(gitDir)) {
      execSync(`rm -rf "${gitDir}"`, { stdio: 'pipe' });
    }

    // 3. Update vertical.config.ts
    const configFile = path.join(projectPath, 'vertical.config.ts');
    if (fs.existsSync(configFile)) {
      const vc = idea.spec.verticalConfig;
      const configContent = `// Auto-generated by business-agent
const config = {
  name: ${JSON.stringify(vc?.name || idea.title)},
  tagline: ${JSON.stringify(vc?.tagline || idea.problem.slice(0, 80))},
  description: ${JSON.stringify(vc?.description || idea.solution.slice(0, 200))},
  primaryColor: ${JSON.stringify(vc?.primaryColor || 'violet')},
  accentColor: ${JSON.stringify(vc?.accentColor || 'purple')},
  features: ${JSON.stringify(vc?.features || idea.spec.coreFeatures)},
  niche: ${JSON.stringify(idea.niche)},
  targetAudience: ${JSON.stringify(idea.targetAudience)},
  monetization: ${JSON.stringify(idea.spec.monetization)},
  seoStrategy: ${JSON.stringify(idea.spec.seoStrategy)},
};

export default config;
`;
      fs.writeFileSync(configFile, configContent, 'utf8');
    }

    // 4. Update package.json name
    const pkgFile = path.join(projectPath, 'package.json');
    if (fs.existsSync(pkgFile)) {
      const pkg = JSON.parse(fs.readFileSync(pkgFile, 'utf8'));
      pkg.name = slug;
      fs.writeFileSync(pkgFile, JSON.stringify(pkg, null, 2), 'utf8');
    }

    // 5. Create GitHub repo
    console.log(`    Creating GitHub repo: ${repoName}...`);
    const cloneUrl = await createGitHubRepo(repoName, idea.problem.slice(0, 100));

    if (!cloneUrl) {
      console.error('    [Scaffold] GitHub repo creation failed — code scaffolded locally only');
    }

    // 6. Init git and push
    const opts = { cwd: projectPath, stdio: 'pipe' as const, timeout: 120_000 };
    execSync('git init', opts);
    execSync('git add -A', opts);
    execSync(`git commit -m "feat: initial scaffold from business-agent — ${idea.title}"`, opts);

    if (cloneUrl) {
      execSync(`git remote add origin ${cloneUrl}`, opts);
      execSync('git branch -M main', opts);
      execSync('git push -u origin main', opts);
      console.log(`    Pushed to GitHub: ${cloneUrl}`);
    }

    // 7. Add to site-watchdog
    const repoUrl = cloneUrl
      ? `https://github.com/${GITHUB_USER}/${repoName}`
      : '';

    addToWatchdog({
      id: slug,
      name: idea.title,
      path: projectPath,
      vercelProject: slug,
      url: idea.domainSuggestions[0] ? `https://${idea.domainSuggestions[0]}` : `https://${slug}.vercel.app`,
      type: 'nextjs',
      youtubeChannel: null,
      focus: ['seo', 'monetization', 'user-engagement'],
      keyFiles: ['app/layout.tsx', 'app/page.tsx', 'vertical.config.ts'],
    });

    return {
      title: idea.title,
      niche: idea.niche,
      score: idea.totalScore,
      repoUrl,
      localPath: projectPath,
      launchedAt: new Date().toISOString(),
    };

  } catch (e: any) {
    console.error(`    [Scaffold failed] ${e.message}`);
    // Cleanup on failure
    if (fs.existsSync(projectPath)) {
      try { execSync(`rm -rf "${projectPath}"`, { stdio: 'pipe' }); } catch {}
    }
    return null;
  }
}
