#!/usr/bin/env npx ts-node
/**
 * AdSense Compliance Generator
 * Creates Privacy Policy, Terms, About, Contact pages + ads.txt + cookie consent
 * for all live projects. Run: npx ts-node adsense-compliance/generate.ts
 */

import * as fs from "fs";
import * as path from "path";

const PUBLISHER_ID = "ca-pub-4237294630161176";
const ADS_TXT = `google.com, pub-4237294630161176, DIRECT, f08c47fec0942fa0\n`;
const CONTACT_EMAIL = "info.siva@gmail.com";

interface ProjectConfig {
  name: string;           // brand name
  dir: string;            // absolute path
  appDir: string;         // "app" or "src/app"
  domain: string;         // full domain e.g. https://kwizzo.app
  description: string;    // one-line what it does
  category: string;       // "entertainment" | "education" | "productivity" | "finance" | "travel" | "health" | "ai-tools"
  style: "dark" | "light"; // colour scheme
}

const PROJECTS: ProjectConfig[] = [
  {
    name: "NammaTamil",
    dir: "/Users/sivaprakasam/projects/agents/nammatamil",
    appDir: "app",
    domain: "https://nammatamil.live",
    description: "Tamil entertainment hub — serials, movies, music and more for the global Tamil diaspora.",
    category: "entertainment",
    style: "dark",
  },
  {
    name: "Kwizzo",
    dir: "/Users/sivaprakasam/projects/agents/kwizzo",
    appDir: "app",
    domain: "https://kwizzo.app",
    description: "AI-powered family quiz game for all ages — play free with no sign-up required.",
    category: "education",
    style: "dark",
  },
  {
    name: "Tutiq",
    dir: "/Users/sivaprakasam/projects/agents/nudge",
    appDir: "app",
    domain: "https://tutiq.app",
    description: "AI personal tutor — personalised learning plans and practice for students of all levels.",
    category: "education",
    style: "dark",
  },
  {
    name: "QuizBites",
    dir: "/Users/sivaprakasam/projects/agents/questly",
    appDir: "app",
    domain: "https://quizbites.app",
    description: "Live classroom quiz platform — teachers run engaging AI-generated quizzes in real time.",
    category: "education",
    style: "dark",
  },
  {
    name: "ResumeVault",
    dir: "/Users/sivaprakasam/projects/agents/ai-resume-builder",
    appDir: "src/app",
    domain: "https://resumevault.app",
    description: "AI resume builder — paste a job description and get a tailored CV in seconds.",
    category: "ai-tools",
    style: "dark",
  },
  {
    name: "DraftCal",
    dir: "/Users/sivaprakasam/projects/agents/social-media-calendar",
    appDir: "src/app",
    domain: "https://draftcal.app",
    description: "AI social media calendar — plan, generate and schedule posts across all platforms.",
    category: "productivity",
    style: "dark",
  },
  {
    name: "TrackWealth",
    dir: "/Users/sivaprakasam/projects/agents/ai-investment-tracker",
    appDir: "src/app",
    domain: "https://trackwealth.app",
    description: "AI investment tracker — monitor portfolios and get AI-powered financial insights.",
    category: "finance",
    style: "dark",
  },
  {
    name: "RoamPlan",
    dir: "/Users/sivaprakasam/projects/agents/ai-travel-planner",
    appDir: "src/app",
    domain: "https://roamplan.app",
    description: "AI travel planner — personalised itineraries, hotel picks and local tips in minutes.",
    category: "travel",
    style: "dark",
  },
  {
    name: "SpeakIQ",
    dir: "/Users/sivaprakasam/projects/agents/language-learning-bot",
    appDir: "src/app",
    domain: "https://speakiq.app",
    description: "AI language learning — conversational practice and gamified lessons for any language.",
    category: "education",
    style: "dark",
  },
  {
    name: "MyVitals",
    dir: "/Users/sivaprakasam/projects/agents/health-tracker",
    appDir: "app",
    domain: "https://myvitals.app",
    description: "AI health tracker — log symptoms, track vitals and get personalised wellness insights.",
    category: "health",
    style: "dark",
  },
  {
    name: "QuizBytes",
    dir: "/Users/sivaprakasam/projects/agents/quizbytesdaily",
    appDir: "app",
    domain: "https://quizbytes.dev",
    description: "Daily AI quiz challenges — fresh trivia every day across science, history, pop culture and more.",
    category: "education",
    style: "dark",
  },
  {
    name: "WorldTrends",
    dir: "/Users/sivaprakasam/projects/agents/worldtrends",
    appDir: "app",
    domain: "https://worldtrends.today",
    description: "Real-time global trends — AI-curated news and trending topics from around the world.",
    category: "ai-tools",
    style: "dark",
  },
  {
    name: "PixelForge",
    dir: "/Users/sivaprakasam/projects/agents/pixelforge",
    appDir: "app",
    domain: "https://arcadeforge.app",
    description: "AI arcade game builder — create and play browser games generated by AI instantly.",
    category: "ai-tools",
    style: "dark",
  },
  {
    name: "ComplyBuddy",
    dir: "/Users/sivaprakasam/projects/agents/complybuddy",
    appDir: "app",
    domain: "https://complyscan.app",
    description: "AI compliance scanner — automatically check websites and documents for regulatory compliance.",
    category: "ai-tools",
    style: "dark",
  },
];

// ─── Templates ────────────────────────────────────────────────────────────────

function privacyPolicyPage(p: ProjectConfig): string {
  const year = new Date().getFullYear();
  return `import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | ${p.name}",
  description: "Privacy policy for ${p.name} — how we collect, use and protect your data.",
  robots: { index: true, follow: true },
};

export default function PrivacyPolicyPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-16 text-sm leading-relaxed">
      <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
      <p className="opacity-50 mb-10">Last updated: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</p>

      <Section title="1. Who We Are">
        <p>${p.name} (${p.domain}) is operated by an independent developer. ${p.description}</p>
        <p className="mt-2">Contact: <a href="mailto:${CONTACT_EMAIL}" className="underline">${CONTACT_EMAIL}</a></p>
      </Section>

      <Section title="2. Information We Collect">
        <p>We may collect the following information when you use our service:</p>
        <ul className="list-disc pl-5 mt-2 space-y-1">
          <li><strong>Usage data</strong> — pages visited, features used, time on site (via analytics).</li>
          <li><strong>Device/browser data</strong> — browser type, operating system, screen resolution, IP address.</li>
          <li><strong>Cookies</strong> — small files stored on your device to remember preferences and enable advertising.</li>
          <li><strong>Account data</strong> (if you register) — email address and profile information you provide.</li>
        </ul>
        <p className="mt-2">We do <strong>not</strong> sell your personal data to third parties.</p>
      </Section>

      <Section title="3. How We Use Your Information">
        <ul className="list-disc pl-5 space-y-1">
          <li>To provide and improve the service.</li>
          <li>To display relevant advertising through Google AdSense.</li>
          <li>To analyse usage patterns and fix bugs.</li>
          <li>To send service-related emails (if you have an account).</li>
        </ul>
      </Section>

      <Section title="4. Google AdSense and Advertising">
        <p>
          We use <strong>Google AdSense</strong> to display advertisements. Google and its partners may use cookies
          to serve ads based on your prior visits to this or other websites. You can opt out of personalised
          advertising by visiting{" "}
          <a href="https://www.google.com/settings/ads" className="underline" target="_blank" rel="noopener noreferrer">
            Google Ads Settings
          </a>.
        </p>
        <p className="mt-2">
          Google's use of advertising cookies is governed by the{" "}
          <a href="https://policies.google.com/privacy" className="underline" target="_blank" rel="noopener noreferrer">
            Google Privacy Policy
          </a>.
        </p>
        <p className="mt-2">
          We participate in the Google AdSense programme. Our ads.txt file confirms our authorised sellers.
        </p>
      </Section>

      <Section title="5. Cookies">
        <p>We use the following types of cookies:</p>
        <ul className="list-disc pl-5 mt-2 space-y-1">
          <li><strong>Essential cookies</strong> — required for basic functionality.</li>
          <li><strong>Analytics cookies</strong> — help us understand how visitors use the site.</li>
          <li><strong>Advertising cookies</strong> — used by Google AdSense to serve relevant ads.</li>
        </ul>
        <p className="mt-2">
          You can control cookies through your browser settings. Blocking advertising cookies will not affect your
          ability to use the site but will show non-personalised ads.
        </p>
      </Section>

      <Section title="6. Third-Party Services">
        <p>We may use the following third-party services, each governed by their own privacy policy:</p>
        <ul className="list-disc pl-5 mt-2 space-y-1">
          <li>Google Analytics / Google AdSense</li>
          <li>Vercel (hosting) — <a href="https://vercel.com/legal/privacy-policy" className="underline" target="_blank" rel="noopener noreferrer">Vercel Privacy Policy</a></li>
          <li>AI providers (Groq, Google Gemini, Anthropic) for generating content on request</li>
        </ul>
      </Section>

      <Section title="7. Data Retention">
        <p>
          We retain usage data for up to 12 months. If you have an account, your data is retained until you
          delete your account or request deletion by emailing us.
        </p>
      </Section>

      <Section title="8. Your Rights (GDPR / CCPA)">
        <p>Depending on your location, you may have the right to:</p>
        <ul className="list-disc pl-5 mt-2 space-y-1">
          <li>Access the personal data we hold about you.</li>
          <li>Request correction or deletion of your data.</li>
          <li>Opt out of personalised advertising.</li>
          <li>Lodge a complaint with your local data protection authority.</li>
        </ul>
        <p className="mt-2">To exercise these rights, email <a href="mailto:${CONTACT_EMAIL}" className="underline">${CONTACT_EMAIL}</a>.</p>
      </Section>

      <Section title="9. Children's Privacy">
        <p>
          This service is not directed at children under 13. We do not knowingly collect personal data from
          children. If you believe a child has provided us with personal information, please contact us.
        </p>
      </Section>

      <Section title="10. Changes to This Policy">
        <p>
          We may update this policy periodically. Changes will be posted on this page with an updated date.
          Continued use of the service constitutes acceptance of the updated policy.
        </p>
      </Section>

      <Section title="11. Contact Us">
        <p>
          For any privacy-related questions, contact us at{" "}
          <a href="mailto:${CONTACT_EMAIL}" className="underline">${CONTACT_EMAIL}</a>.
        </p>
      </Section>

      <p className="mt-10 opacity-40 text-xs">© ${year} ${p.name}. All rights reserved.</p>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-semibold mb-3">{title}</h2>
      {children}
    </section>
  );
}
`;
}

function termsPage(p: ProjectConfig): string {
  const year = new Date().getFullYear();
  return `import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | ${p.name}",
  description: "Terms of service for ${p.name} — your rights and responsibilities when using our service.",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-16 text-sm leading-relaxed">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="opacity-50 mb-10">Last updated: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</p>

      <Section title="1. Acceptance of Terms">
        <p>
          By accessing or using ${p.name} (${p.domain}), you agree to be bound by these Terms of Service.
          If you do not agree, please do not use the service.
        </p>
      </Section>

      <Section title="2. Description of Service">
        <p>${p.description}</p>
        <p className="mt-2">
          The service is provided free of charge. We reserve the right to modify, suspend or discontinue
          the service at any time without notice.
        </p>
      </Section>

      <Section title="3. User Conduct">
        <p>You agree not to:</p>
        <ul className="list-disc pl-5 mt-2 space-y-1">
          <li>Use the service for any unlawful purpose.</li>
          <li>Attempt to gain unauthorised access to any part of the service.</li>
          <li>Interfere with or disrupt the service or its servers.</li>
          <li>Scrape, crawl or harvest data from the service without written permission.</li>
          <li>Use the service to distribute spam, malware or harmful content.</li>
          <li>Misrepresent your identity or affiliation.</li>
        </ul>
      </Section>

      <Section title="4. AI-Generated Content">
        <p>
          Parts of this service use artificial intelligence to generate content. AI-generated content may
          contain errors, inaccuracies or outdated information. You should independently verify any
          important information before relying on it. We are not liable for decisions made based on
          AI-generated output.
        </p>
      </Section>

      <Section title="5. Intellectual Property">
        <p>
          All original content, design and code on this service is owned by or licensed to ${p.name}.
          You may not reproduce, distribute or create derivative works without our written permission.
        </p>
        <p className="mt-2">
          User-submitted content (if applicable) remains your property. By submitting content, you grant
          us a non-exclusive, royalty-free licence to use it to provide the service.
        </p>
      </Section>

      <Section title="6. Third-Party Links and Services">
        <p>
          The service may contain links to third-party websites. We are not responsible for the content,
          privacy practices or accuracy of any third-party sites. Visiting third-party links is at your
          own risk.
        </p>
      </Section>

      <Section title="7. Advertising">
        <p>
          This service displays advertisements provided by Google AdSense and other advertising networks.
          Advertisements are clearly labelled. We do not endorse advertisers or their products.
        </p>
      </Section>

      <Section title="8. Disclaimer of Warranties">
        <p>
          The service is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied.
          We do not warrant that the service will be uninterrupted, error-free or free of viruses.
          Use the service at your own risk.
        </p>
      </Section>

      <Section title="9. Limitation of Liability">
        <p>
          To the fullest extent permitted by law, ${p.name} shall not be liable for any indirect,
          incidental, special or consequential damages arising from your use of the service, even if
          we have been advised of the possibility of such damages.
        </p>
      </Section>

      <Section title="10. Governing Law">
        <p>
          These terms are governed by the laws of England and Wales. Any disputes shall be subject to
          the exclusive jurisdiction of the courts of England and Wales.
        </p>
      </Section>

      <Section title="11. Changes to These Terms">
        <p>
          We may update these terms at any time. We will post the updated terms on this page with a new
          effective date. Continued use of the service constitutes acceptance of the updated terms.
        </p>
      </Section>

      <Section title="12. Contact">
        <p>
          Questions about these terms? Email us at{" "}
          <a href="mailto:${CONTACT_EMAIL}" className="underline">${CONTACT_EMAIL}</a>.
        </p>
      </Section>

      <p className="mt-10 opacity-40 text-xs">© ${year} ${p.name}. All rights reserved.</p>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-semibold mb-3">{title}</h2>
      {children}
    </section>
  );
}
`;
}

function aboutPage(p: ProjectConfig): string {
  const year = new Date().getFullYear();
  return `import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About | ${p.name}",
  description: "About ${p.name} — ${p.description}",
  robots: { index: true, follow: true },
};

export default function AboutPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-16 text-sm leading-relaxed">
      <h1 className="text-3xl font-bold mb-6">About ${p.name}</h1>

      <section className="mb-8">
        <p className="text-base leading-7">${p.description}</p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold mb-3">What We Offer</h2>
        <p>
          ${p.name} is a free service built to make ${p.category === "education" ? "learning" : p.category === "entertainment" ? "entertainment" : p.category === "finance" ? "financial tracking" : p.category === "health" ? "health monitoring" : p.category === "travel" ? "travel planning" : "productivity"} more accessible through the power of artificial intelligence.
          Our tools are designed to be intuitive, fast and available to everyone — no subscription required to get started.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold mb-3">Built with AI</h2>
        <p>
          We use state-of-the-art AI models to deliver personalised, high-quality results. Our systems
          are continuously improving based on user feedback and the latest advances in AI research.
          All AI-generated content is clearly presented as such — we believe in transparency.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold mb-3">Privacy First</h2>
        <p>
          We collect only the data necessary to provide the service. We do not sell your data to third
          parties. See our{" "}
          <a href="/privacy" className="underline">Privacy Policy</a> for full details.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold mb-3">Advertising</h2>
        <p>
          ${p.name} is supported by advertising through Google AdSense. Ads help us keep the service
          free for everyone. We work to ensure ads are relevant and non-intrusive.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold mb-3">Get in Touch</h2>
        <p>
          We&apos;d love to hear from you — feedback, bug reports or partnership enquiries are all welcome.
          Reach us at{" "}
          <a href="mailto:${CONTACT_EMAIL}" className="underline">${CONTACT_EMAIL}</a> or use our{" "}
          <a href="/contact" className="underline">contact page</a>.
        </p>
      </section>

      <p className="mt-10 opacity-40 text-xs">© ${year} ${p.name}. All rights reserved.</p>
    </main>
  );
}
`;
}

function contactPage(p: ProjectConfig): string {
  const year = new Date().getFullYear();
  return `"use client";
import type { Metadata } from "next";
import { useState } from "react";

// Note: metadata must be in a separate server component if needed.
// For now, this client component handles the form.

export default function ContactPage() {
  const [submitted, setSubmitted] = useState(false);

  return (
    <main className="max-w-2xl mx-auto px-4 py-16 text-sm leading-relaxed">
      <h1 className="text-3xl font-bold mb-2">Contact Us</h1>
      <p className="opacity-50 mb-10">${p.name} — ${p.domain}</p>

      <div className="mb-8">
        <p>
          Have a question, feedback or found a bug? We&apos;d love to hear from you.
          Email us directly at{" "}
          <a href="mailto:${CONTACT_EMAIL}" className="underline font-medium">${CONTACT_EMAIL}</a>
        </p>
      </div>

      <div className="mb-8">
        <h2 className="text-lg font-semibold mb-3">Common enquiries</h2>
        <ul className="list-disc pl-5 space-y-2 opacity-70">
          <li><strong>Bug reports</strong> — describe the issue and steps to reproduce it.</li>
          <li><strong>Feature requests</strong> — tell us what you&apos;d like to see.</li>
          <li><strong>Privacy / data requests</strong> — see our <a href="/privacy" className="underline">Privacy Policy</a> for your rights.</li>
          <li><strong>Advertising</strong> — for ad-related queries, contact Google AdSense directly.</li>
          <li><strong>Copyright / DMCA</strong> — include the infringing URL and your ownership evidence.</li>
        </ul>
      </div>

      <div className="p-4 rounded-xl border border-white/10 bg-white/[0.02]">
        <p className="font-medium mb-1">Email</p>
        <a href="mailto:${CONTACT_EMAIL}" className="underline opacity-70">${CONTACT_EMAIL}</a>
        <p className="mt-3 opacity-40 text-xs">We aim to respond within 2 business days.</p>
      </div>

      <p className="mt-10 opacity-40 text-xs">© ${year} ${p.name}. All rights reserved.</p>
    </main>
  );
}
`;
}

function cookieConsentComponent(): string {
  return `"use client";
import { useState, useEffect } from "react";
import Link from "next/link";

const COOKIE_KEY = "cookie_consent_v1";

export default function CookieConsent() {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const consent = localStorage.getItem(COOKIE_KEY);
    if (!consent) setVisible(true);
  }, []);

  function accept() {
    localStorage.setItem(COOKIE_KEY, "accepted");
    setVisible(false);
  }

  function decline() {
    localStorage.setItem(COOKIE_KEY, "declined");
    setVisible(false);
  }

  if (!visible) return null;

  return (
    <div
      role="dialog"
      aria-label="Cookie consent"
      className="fixed bottom-0 left-0 right-0 z-50 p-4 md:p-6 bg-zinc-950/95 border-t border-white/10 backdrop-blur-sm"
    >
      <div className="max-w-4xl mx-auto flex flex-col sm:flex-row items-start sm:items-center gap-4">
        <div className="flex-1 text-sm text-white/70">
          <p>
            We use cookies to improve your experience and show relevant ads via{" "}
            <strong className="text-white">Google AdSense</strong>. By clicking
            &ldquo;Accept&rdquo; you consent to our use of cookies.{" "}
            <Link href="/privacy" className="underline text-white/90">
              Privacy Policy
            </Link>
            {" · "}
            <Link href="/terms" className="underline text-white/90">
              Terms
            </Link>
          </p>
        </div>
        <div className="flex gap-3 shrink-0">
          <button
            onClick={decline}
            className="px-4 py-2 text-xs rounded-lg border border-white/20 text-white/60 hover:border-white/40 hover:text-white/80 transition-colors"
          >
            Decline
          </button>
          <button
            onClick={accept}
            className="px-4 py-2 text-xs rounded-lg bg-white text-black font-medium hover:bg-white/90 transition-colors"
          >
            Accept all cookies
          </button>
        </div>
      </div>
    </div>
  );
}
`;
}

// ─── Runner ───────────────────────────────────────────────────────────────────

interface AuditResult {
  project: string;
  domain: string;
  checks: { name: string; status: "ok" | "created" | "skipped" | "error"; note?: string }[];
}

function writeIfMissing(filePath: string, content: string): "created" | "skipped" {
  if (fs.existsSync(filePath)) return "skipped";
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  return "created";
}

function run() {
  const results: AuditResult[] = [];

  for (const p of PROJECTS) {
    if (!fs.existsSync(p.dir)) {
      console.log(`⏭  ${p.name}: dir not found, skipping`);
      continue;
    }

    const appPath = path.join(p.dir, p.appDir);
    const publicPath = path.join(p.dir, "public");
    const componentsPath = path.join(p.dir, "components");
    const result: AuditResult = { project: p.name, domain: p.domain, checks: [] };

    // 1. ads.txt
    const adsTxtPath = path.join(publicPath, "ads.txt");
    const adsTxtExisting = fs.existsSync(adsTxtPath) ? fs.readFileSync(adsTxtPath, "utf8") : "";
    if (adsTxtExisting.includes("pub-4237294630161176")) {
      result.checks.push({ name: "ads.txt", status: "skipped", note: "already has publisher ID" });
    } else {
      fs.mkdirSync(publicPath, { recursive: true });
      fs.writeFileSync(adsTxtPath, ADS_TXT, "utf8");
      result.checks.push({ name: "ads.txt", status: "created" });
    }

    // 2. Privacy Policy
    const privacyDir = path.join(appPath, "privacy");
    const privacyStatus = writeIfMissing(path.join(privacyDir, "page.tsx"), privacyPolicyPage(p));
    result.checks.push({ name: "privacy page", status: privacyStatus });

    // 3. Terms
    const termsDir = path.join(appPath, "terms");
    const termsStatus = writeIfMissing(path.join(termsDir, "page.tsx"), termsPage(p));
    result.checks.push({ name: "terms page", status: termsStatus });

    // 4. About
    const aboutDir = path.join(appPath, "about");
    const aboutStatus = writeIfMissing(path.join(aboutDir, "page.tsx"), aboutPage(p));
    result.checks.push({ name: "about page", status: aboutStatus });

    // 5. Contact
    const contactDir = path.join(appPath, "contact");
    const contactStatus = writeIfMissing(path.join(contactDir, "page.tsx"), contactPage(p));
    result.checks.push({ name: "contact page", status: contactStatus });

    // 6. CookieConsent component — source of truth: shared-ui/src/ui/CookieConsent.tsx
    fs.mkdirSync(componentsPath, { recursive: true });
    const cookieStatus = writeIfMissing(
      path.join(componentsPath, "CookieConsent.tsx"),
      cookieConsentComponent()
    );
    result.checks.push({ name: "CookieConsent component", status: cookieStatus });

    // 7. Footer component — source of truth: shared-ui/src/layout/Footer.tsx
    const sharedFooterSrc = path.join(
      "/Users/sivaprakasam/projects/agents/shared-ui/src/layout/Footer.tsx"
    );
    const footerDest = path.join(componentsPath, "Footer.tsx");
    if (!fs.existsSync(footerDest)) {
      if (fs.existsSync(sharedFooterSrc)) {
        fs.copyFileSync(sharedFooterSrc, footerDest);
        result.checks.push({ name: "Footer component", status: "created" });
      } else {
        result.checks.push({ name: "Footer component", status: "error", note: "shared-ui source not found" });
      }
    } else {
      result.checks.push({ name: "Footer component", status: "skipped", note: "already exists" });
    }

    results.push(result);
  }

  // ─── Print report ─────────────────────────────────────────────────────────
  console.log("\n╔══════════════════════════════════════════════════╗");
  console.log("║     AdSense Compliance Generator — Report        ║");
  console.log("╚══════════════════════════════════════════════════╝\n");

  for (const r of results) {
    const created = r.checks.filter(c => c.status === "created").length;
    const ok = r.checks.filter(c => c.status === "skipped").length;
    console.log(`\n📦 ${r.project} (${r.domain})`);
    for (const c of r.checks) {
      const icon = c.status === "created" ? "✅" : c.status === "skipped" ? "⚪" : c.status === "error" ? "❌" : "✅";
      const label = c.status === "created" ? "CREATED" : c.status === "skipped" ? "EXISTS " : "ERROR  ";
      console.log(`   ${icon} ${label}  ${c.name}${c.note ? ` (${c.note})` : ""}`);
    }
  }

  const totalCreated = results.flatMap(r => r.checks).filter(c => c.status === "created").length;
  console.log(`\n✨ Done. Created ${totalCreated} new files across ${results.length} projects.\n`);
  console.log("⚠️  REMAINING STEPS:");
  console.log("   1. Wire <CookieConsent /> + <Footer siteName='...' /> into each layout.tsx");
  console.log("      (already done if run inject_cookie.sh + kwizzo migration)");
  console.log("   2. Commit and push each project to trigger Vercel deploy");
  console.log("   3. Run audit.ts after deploy to verify all pages return HTTP 200");
  console.log("   4. To update Footer/CookieConsent across all projects:");
  console.log("      Edit shared-ui/src/layout/Footer.tsx or shared-ui/src/ui/CookieConsent.tsx");
  console.log("      then re-run this script (it will skip existing, use --force flag to overwrite)");
  console.log("");
}

run();
